# Generated by Django 2.1 on 2019-09-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dailyattendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('ispresent', models.IntegerField(blank=True, db_column='isPresent', null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('updatead_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '$dailyAttendance',
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('ispresent', models.IntegerField(blank=True, db_column='isPresent', null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('updatead_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '$proxy',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_id', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=20, null=True)),
                ('lec_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '$timeTable',
            },
        ),
    ]
