# Generated by Django 2.1 on 2019-09-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_controller', '0002_remove_dailyattendance_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='subject',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
